version: "3"

services:
  redis:
    image: redis:7.0.8
    container_name: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 2s

  url-shortener:
    image: ghcr.io/curt-park/url-shortener:latest
    build: .
    container_name: url-shortener
    ports:
      - 8080:8080
    volumes:
      - ./config/docker.yaml:/config/default.yaml
    depends_on:
      redis:
        condition: service_healthy
    links:
      - redis
    # restart: always
