kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      additionalScrapeConfigs:
        - job_name: url-shortener
          scrape_interval: 15s
          metrics_path: /metrics
          scheme: http
          kubernetes_sd_configs:
          - role: endpoints
          relabel_configs:
          - source_labels: [__meta_kubernetes_pod_node_name]
            action: replace
            target_label: kubernetes_node
  grafana:
    adminPassword: prom-operator
    service:
      type: ClusterIP
      port: 3000

  ingress:
    enabled: false
    ingressClassName: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # traefik.ingress.kubernetes.io/rewrite-target: /
    labels:
      # app.kubernetes.io/instance: prometheus
      # app.kubernetes.io/name: grafana
    ## Redirect ingress to an additional defined port on the service
    # servicePort: 3000
    hosts: ""
    paths: {}
    ## TLS configuration for Alertmanager Ingress
    ## Secret must be manually created in the namespace
    tls: []
    # - secretName: alertmanager-general-tls
    #   hosts:
    #   - alertmanager.example.com
