annotations:
  category: Database
  licenses: Apache-2.0
apiVersion: v2
appVersion: 7.0.8
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x.x
description: Redis(R) is an open source, scalable, distributed in-memory cache for
  applications. It can be used to store and serve data in the form of strings, hashes,
  lists, sets and sorted sets.
home: https://github.com/bitnami/charts/tree/main/bitnami/redis-cluster
icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
keywords:
- redis
- keyvalue
- database
maintainers:
- name: Bitnami
  url: https://github.com/bitnami/charts
name: redis-cluster
sources:
- https://github.com/bitnami/containers/tree/main/bitnami/redis
- http://redis.io/
version: 8.3.5
